# Generated by Django 5.0.2 on 2025-07-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
    ]
